### ISSUE TITLE
client side behavior of Skill/HoldableSkill/StatusEffect is "duplicated" on each player respawn and is not cleared

### ISSUE THREAD

**Issue by notkannon** [g1mmethemoney/WCSTypescript#17]
If I describe the problem even more simply and clearly, then I have my own Character component on the server and the client, on the server the WCSCharacter object is mainly managed, created and deleted. As I wrote in the title, this only happens on the client. That is, indeed, the server does not have such a problem (i guess).
![image](https://github.com/user-attachments/assets/956e3a83-28a7-4b33-a6b2-8b5e4d8a6883)
![image](https://github.com/user-attachments/assets/7ca1ee0b-cee8-43f8-b0d9-ec20182b2e28)
![image](https://github.com/user-attachments/assets/74e05795-6c59-4f62-bab7-7edb1b260ae4)
in Output you can see that the skill is removed twice at the same time, on the last respawn (yes, this doesn't always work with skills. But now let's look at the status effects) _(the status effects have the same way of calling the methods of the base implementation and the child)_
![image](https://github.com/user-attachments/assets/601bce82-6514-4247-8f30-8a8c01c369c8)
![image](https://github.com/user-attachments/assets/d9b4db3e-4a0c-47e8-b436-bfe5e7cc3c19)
here you can clearly see that they "overlap" each other on the client, but on the server everything happens linearly and stably.

I use own base extension implementations with additional logic for my own WCS objects for convenience, but I don't think that the problem is in them (at least I haven't checked it and I don't know how it can be related to client-only behavior).
![image](https://github.com/user-attachments/assets/6962a136-ae56-4b8b-a267-4c5550e80c3e)

I really hope that my explanation of the problem will give some understanding of a possible solution, because I am ready to put here all my code that is in the project, but I don’t think you will have time to read it. Or I’m a fool and doing something wrong.

My current WCS version: 2.4.1
I don’t use roblox-ts, I use the Roblox Studio development environment.

**Comment by wad4444** [comment]
closed / not wcs at fault
